// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9wGE1Vo6ugoBUzM18C4SP3nWC4tiWn3M',
    appId: '1:743937583356:web:508872613a63accd178f79',
    messagingSenderId: '743937583356',
    projectId: 'billzify-app',
    authDomain: 'billzify-app.firebaseapp.com',
    storageBucket: 'billzify-app.firebasestorage.app',
    measurementId: 'G-PT1CG37WVJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApGALb-j2BmOUKaFJbGs-xDm5EsD6oCu0',
    appId: '1:743937583356:android:0c33049c9ab1767d178f79',
    messagingSenderId: '743937583356',
    projectId: 'billzify-app',
    storageBucket: 'billzify-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBl-zuWwMKU4zq2FPaED5G39hKHt9M3KUY',
    appId: '1:743937583356:ios:bad785456300f042178f79',
    messagingSenderId: '743937583356',
    projectId: 'billzify-app',
    storageBucket: 'billzify-app.firebasestorage.app',
    iosBundleId: 'com.billzify.cm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBl-zuWwMKU4zq2FPaED5G39hKHt9M3KUY',
    appId: '1:743937583356:ios:ac3fa62b34ab4be4178f79',
    messagingSenderId: '743937583356',
    projectId: 'billzify-app',
    storageBucket: 'billzify-app.firebasestorage.app',
    iosBundleId: 'com.cmapps.cmFlutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9wGE1Vo6ugoBUzM18C4SP3nWC4tiWn3M',
    appId: '1:743937583356:web:62a7a5bfd5e77a3b178f79',
    messagingSenderId: '743937583356',
    projectId: 'billzify-app',
    authDomain: 'billzify-app.firebaseapp.com',
    storageBucket: 'billzify-app.firebasestorage.app',
    measurementId: 'G-4X9HD2Q251',
  );
}
